name: demo ci

on:
  workflow_dispatch:

jobs:
  build-using-maven:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print working directory
        run: pwd

  
